version: '3.4'
services:
  provider-api:
    build:
      context: .
      dockerfile: ./docker/dev.dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/

    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    links:
      - substrate-node
      - mongodb
    extra_hosts:
      - "host.docker.internal:host-gateway"
  mongodb:
    image: mongo:5.0.4
    volumes:
      - ./mongodb/:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
  substrate-node:
    image: prosopo/substrate:monthly-2022-03
    build:
      context: ./docker/
      dockerfile: Substrate.dockerfile
    ports:
      - "9615:9615"
      - "9944:9944"
      - "9933:9933"